### ISSUE TITLE
Customize / Override Link Tags

### ISSUE THREAD

**Issue by valZho** [goldsky/Lingua#26]
When using Lingua, link tags (e.g. [[~4]]) should be language-specific. As it is, the link tags always return the default link (i.e., the non-lingua uri data).

In the meantime, I had to create a custom snippet to use instead of the link tag... but that can get pretty unwieldy...

**Comment by goldsky** [comment]
the proper way is by adding language parameter into the link
```[[~4? &lang=`[[!lingua.cultureKey]]`]]```

**Comment by goldsky** [comment]
After some investigation, there's no way to override Link Tags.
https://github.com/modxcms/revolution/blob/master/core/model/modx/modparser.class.php#L470
