### ISSUE TITLE
lingua.getValue Snippet doesn't default properly

### ISSUE THREAD

**Issue by valZho** [goldsky/Lingua#27]
When using the lingua.getValue snippet, data is not pulled from the default language. This bug affects not only instances when the selected translation isn't available, but instances where the default language is the one selected; in either case, lingua.getValue will return nothing.

This snippet should always return the value for the default language (i.e., the value from modx_site_content) if the translated value doesn't exist (i.e., the value from modx_lingua_site_content).

To get around this problem, I had to write the following wrapper snippet that I call instead of lingua.getValue:

    // initialize
    $vars = array(
    	'id'=>$id,
    	'field'=>$field
    );
    
    // get translated field
    $field = $modx->runSnippet('lingua.getValue', $vars);
    
    // if no translation, then get default
    if (empty($field)) {
    	$field = $modx->runSnippet('getResourceField', $vars);
    }

**Comment by valZho** [comment]
Actually, I had to modify the snippet to accommodate template variables as follows:

    <?php
    // $id = id of the resource
    // $field = the field to retrieve
    // $tv = the name of the TV field to retrieve (leave field blank)
    
    if ($id==0 || (empty($field) && empty($tv)) ) { return ''; }

    // initialize
    $vars = array(
        'id'=>$id,
        'field'=> (empty($field)?$tv:$field),
        'isTV'=> (empty($field)?1:0),
        'processTV'=>(empty($field)?1:0)
    );

    // get translated field
    $output = $modx->runSnippet('lingua.getValue', $vars);

    // if no translation, then get default
    if (empty($output)) {
        $output = $modx->runSnippet('getResourceField', $vars);
    }
    
    // send back string
    return $output;

**Comment by goldsky** [comment]
I'll make another work around.
Depending on another snippet is not my choice.

**Comment by goldsky** [comment]
On the second thought, this behavior is intended.
If you have empty value on a language, it should return empty.
There is no "default value".
There's only "default language", just to identify the applied language to the original MODX's content.

**Comment by valZho** [comment]
That's fine if it's intended behavior, but it is then inconsistent with the behavior of rendering a page. When I create a resource in MODX, and don't enter anything in a field on a translation, then MODX will pull the data from the main resource, i.e., the default language. This is a very useful feature as not everything needs a translation. Should the snippet that allows you to get a field from something that isn't the current page have the same behavior as using a tag for the current page? You could make things consistent by either:

1. Make the snippets return the field for the default language if the requested translation isn't available.
2. Have translated fields return empty on page render if they are empty rather than delivering the data from the default language.

Personally, I vote for number 1 as it's much more useful. As I said, not everything needs to be translated, but with the no-default method you have to make sure that you copy all fields into every language.

Also, I don't know if this belongs in a different issue report or not, but calling lingua.getValue will always return empty when the default language is selected on the front end, i.e., it will *only* return "translated" data and nothing from the default language. (and don't tell me that I should be using some type of filter to test for empty results or the default language code and then pull the default language data ...because that's just silly, unnecessarily long, and counter-intuitive).

**Comment by goldsky** [comment]
> That's fine if it's intended behavior, but it is then inconsistent with the behavior of rendering a page. When I create a resource in MODX, and don't enter anything in a field on a translation, then MODX will pull the data from the main resource, i.e., the default language.

I realized the odd too, so I've made another [commit](https://github.com/goldsky/Lingua/commit/02104f9a4d6526619b8036500f427ef0c356c667#diff-790345c28f8043e79a44fa33e9a66441L246) yesterday.

Anyway,
May be it's better to add a system setting, to allow user to choose how Lingua should return if a field is empty.

**Comment by goldsky** [comment]
On this update, you can use ```[[!lingua.getValue? &field=`description` &emptyReturnsDefault=`1`]]``` for snippet call, or just set `lingua.empty_returns_default` in System Setting as "Yes" for global scope.
