### ISSUE TITLE
Need batch update for imported resources

### ISSUE THREAD

**Issue by outre99** [goldsky/Lingua#30]
After the initial import with ImportX the resources exist in the modx_site_content and in template variables tables because the default language values were included in the import.

At this point i'd like to update just the translated values in lingua tables but the newly imported resources don't exist there yet. They are only copied after a resource is edited in the manager and saved. I'm wondering if there's a way to make lingua pickup the newly imported resources in batch and insert them into its tables. At which point a simple sql update to add translated values into lingua tables can be done.

**Comment by goldsky** [comment]
Next update:
![sync](https://cloud.githubusercontent.com/assets/308524/6020059/edfd5d1e-abd9-11e4-8a34-80435c7d773a.png)

**Comment by outre99** [comment]
Brilliant.  Thanks for the quick turn-around.
