### ISSUE TITLE
Different Language Settings per Context / Parent / Resource

### ISSUE THREAD

**Issue by valZho** [goldsky/Lingua#31]
As someone building out a multi-site MODX install using a single manager with different contexts, it occurs to me that language activation needs to happen at the context level and not the global level. Some sites may have different sets of translations than others, and some may not have any at all.

To piggyback onto [this feature request](https://github.com/goldsky/Lingua/issues/29), the CMP for Lingua should probably be rewritten a bit. The current "Settings" tab should remain mostly unchanged except to rename the tab "Languages" and remove the "Active" setting. Then add a new tab: "Contexts" where you can assign languages to contexts and mark them as active or inactive.

If a language is assigned to a context, it can be selected in the editor for that context's resources. If it is marked as active then that translation will also be selectable on the front-end.

This would, of course, replace the lingua.contexts system setting.

If you want to get really fancy and replace the lingua.ids and lingua.parents settings, you could add two more tabs: "Resources" and "Parents" that allow you to assign languages to each respectively. I imagine, though, that that could get mighty tricky. Maybe on the "Contexts" tab, have a place where you can enter resource/parent IDs on the context to indicate specific resources that the settings (at the context level) should apply to. Kind of a hybrid of the current system and the new.

**Comment by goldsky** [comment]
Do you know that MODX's system selecting properties descending?
`$modx->getOption('thing', $scriptProperties, 'defaultValue')` takes the value from top to down:

* System Settings
* Context Settings
* Property Sets
* Default element's (snippet, plugin, template, or chunk) properties
    * On their "Properties" tab
    * Inside the PHP script
* Element's inline call properties (using `&`)

I might miss it on the rtfm, but if you want one of your context has different language set, just edit the context's setting, and add `lingua.langs` key, fill the values with comma separated language code, eg: `es,en`. This will override that global "Active" setting.

So,
> This would, of course, replace the lingua.contexts system setting

No, it stays to keep the global scope.

> If you want to get really fancy and replace the lingua.ids and lingua.parents settings, you could add two more tabs: "Resources" and "Parents" that allow you to assign languages to each respectively. I imagine, though, that that could get mighty tricky. Maybe on the "Contexts" tab, have a place where you can enter resource/parent IDs on the context to indicate specific resources that the settings (at the context level) should apply to. Kind of a hybrid of the current system and the new.

Back to that **descended properties**.

I know MODX has documentation about this somewhere, but I lost the link.

**Comment by valZho** [comment]
That would be ~~great~~ doable if it works. It's not at all obvious that this is possible as there is no lingua.langs key in the system settings, and the only activate/deactivate option for languages is in the CMP (i.e., global).

I would still much prefer to have a tab in the CMP where you can assign languages to a context (as described above); it's just MUCH better UX.

Barring that, remove the "Active" check box, create the lingua.langs system setting, and document it somewhere so someone who knows MODX (and cascading preferences) could easily figure it how to customize each context.

Just my two cents! Thanks for making such a great extra!

**Comment by goldsky** [comment]
Next update.

![scopes](https://cloud.githubusercontent.com/assets/308524/5988950/9aab08d8-a9a8-11e4-8d33-5686b9291cd8.png)

**Comment by 4ntz** [comment]
I think this is a great feature - especially to exclude Resources. However, I got a question: why do the excluded Resources still appear in each language in the Wayfinder Menu (Frontend)? For example: I have set a Resource to use only the language "de", but on the Frontend when the Language "en" is selected, the Resource still shows up in the Menu and can be accessed by the user. Is this a bug or is it meant to work like that? I would love to see the Resource not showing up in the Menu, as it should not "exist" in the "en" Version of my website.

**Comment by goldsky** [comment]
It would need new snippets to replace WF and gR.

**Comment by 4ntz** [comment]
New WF & gR snippets or new Lingua snippets? If it is about the Lingua snippets - are you planning to do something about that?

**Comment by goldsky** [comment]
New Lingua snippets.

I don't think changing original WF and gR is the wise choice, but I would
just fork them and adjust it for Lingua, so all properties would be the
same.

Well, if anyone can buy me some donuts and coffee, I can start to build it.
:D

**Comment by 4ntz** [comment]
Fair enough! :) Check your Emails..
