### ISSUE TITLE
Language Switching Bug w/ Rich Text Settings

### ISSUE THREAD

**Issue by valZho** [goldsky/Lingua#35]
I just ran across this bug that had me stumped—took me forever to even figure out what was causing the issue. I'm still not 100% sure that this isn't just something quirky with my build, but the fix won't break anything even if that's the case.

**Behavior:**
When a resource is set to Rich Text but you don't have a rich text editor installed, switching between languages gets really wonky. Some language content fields don't show up at all, and others are sized improperly.

**Problem:**
In the resource.js file if a resource is set as rich text, the js tests to see if MODx.ux.CKEditor is defined. However, MODx.ux is itself undefined—and since you can't test a property of "undefined", js kicks back an error causing the content field switching to fail in odd ways.

**Solution:**
Test MODx.ux *before* testing MODx.ux.CKEditor. In the resource.js file, replace lines 229–231 with the following:

    if (typeof(MODx.ux) !== 'undefined') {
        if (typeof(MODx.ux.CKEditor) !== 'undefined') {
            MODx.ux.CKEditor.replaceComponent(this.getId());
        }
    }

**Comment by goldsky** [comment]
I think this is related with https://github.com/goldsky/Lingua/issues/23
