### ISSUE TITLE
Compatibility with ContentBlocks

### ISSUE THREAD

**Issue by eminos** [goldsky/Lingua#39]
I would love for Lingua to be compatible with modmore ContentBlocks :)
https://www.modmore.com/extras/contentblocks/bugs/

**Comment by goldsky** [comment]
It's is confirmed that they can't play together.
I've added this incompatibility in http://rtfm.modx.com/extras/revo/lingua
ContentBlocks hides and replaces the textarea, while Lingua switches that hidden textarea.
