### ISSUE TITLE
TV saving problem: second language should have empty value

### ISSUE THREAD

**Issue by 4ntz** [goldsky/Lingua#48]
I can not save TV's where the second language has an empty value. After saving and refreshing (Backend) I always get the value of my main language in my second language. Happens with imageTV's, MIGX TV's,...

Example: Main language is German, second language is English.

imageTV (DE selected): imagename-DE.jpg
imageTV (EN selected): imagename-EN.jpg

When I delete the file from the second language:

imageTV (DE selected): imagename-DE.jpg
imageTV (EN selected):

hit save and refresh the page, i get this:

imageTV (DE selected): imagename-DE.jpg
imageTV (EN selected): imagename-DE.jpg

**Comment by goldsky** [comment]
is this using https://rtfm.modx.com/extras/revo/migx/migx.backend-usage ?

**Comment by 4ntz** [comment]
Yes, but not only with MIGX. It also happens with normal TV's (textTV, imageTV,...)

**Comment by 4ntz** [comment]
This also happens when I leave the value of the second language empty on first try.

imageTV (DE selected): imagename-DE.jpg
imageTV (EN selected):

save + refresh, then I get this:

imageTV (DE selected): imagename-DE.jpg
imageTV (EN selected): imagename-DE.jpg

**Comment by 4ntz** [comment]
Is there anything I can do to help solving this? Still having problems with this..

**Comment by goldsky** [comment]
Related:
* https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L349
* https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L188
