### ISSUE TITLE
MIGX + Lingua + MODX 2.7

### ISSUE THREAD

**Issue by ZTX18** [goldsky/Lingua#61]
-Create a new site
-install lingua
-install migx
-go to migx configs - create a new one
-create a new migx TV, set that config
-add this TV to lingua

Default language is ok, in other languages Lingua just hides this TV
(It seems, that it can not copy migx tv in 2.7.0).
I've checked all ids - cloneIds, they are ok, (i think so)
How to trace what's going wrong?

**Comment by goldsky** [comment]
Seems the id and cloned id don't match

**Comment by ZTX18** [comment]
Problem with pdoTools useFenom option, sorry.

For those who have the same problem:
To fix - just don't use Fenom when processing Lingua's chunks


in 
> public function processElementTags

add before processing:
`if($this->modx->parser->pdoTools)$this->modx->parser->pdoTools->config['useFenom'] = false;`
